from pathlib import Path

path = Path('src/App.jsx')
text = path.read_text(encoding='utf-8')

if "import AnnualPurchasePanel" not in text:
    text = text.replace("import EpubReader from './EpubReader.jsx'", "import EpubReader from './EpubReader.jsx'\nimport AnnualPurchasePanel from './AnnualPurchasePanel.jsx'")

busy_line = "  const [annualPurchaseBusy,setAnnualPurchaseBusy]=useState(false)"
message_line = "  const [annualPurchaseMessage,setAnnualPurchaseMessage]=useState('')"
return_line = "  const [paymentReturn,setPaymentReturn]=useState(null)"
while text.count(busy_line) > 1:
    text = text.replace(busy_line + "\n" + message_line + "\n" + busy_line + "\n" + message_line, busy_line + "\n" + message_line, 1)
if busy_line not in text:
    text = text.replace("  const [acceptedTerms,setAcceptedTerms]=useState(false)", "  const [acceptedTerms,setAcceptedTerms]=useState(false)\n" + busy_line + "\n" + message_line)
if return_line not in text:
    text = text.replace(message_line, message_line + "\n" + return_line, 1)

old = """  async function openEncounter(dayNumber = 1) {\n    if (!user && (dayNumber < 1 || dayNumber > 3)) { setScreen('signup'); setMessage('Crie sua conta para continuar além da prévia gratuita.'); return }"""
new = """  async function openEncounter(dayNumber = 1) {\n    if (!user) { setScreen('guestDemo'); setMessage('Os encontros completos fazem parte da edição anual 2027. Crie sua conta e adquira o acesso premium para começar sua caminhada.'); return }"""
text = text.replace(old, new)

text = text.replace("<small>O cadastro é gratuito nesta etapa. Nenhuma cobrança será realizada agora.</small>", "<small>A criação da conta não gera cobrança. Você poderá conhecer o aplicativo e adquirir separadamente o acesso premium Bíblia + Chimarrão — Edição 2027.</small>")
text = text.replace("<small>A criação da conta não gera cobrança. Depois de confirmar seu cadastro, você poderá revisar e adquirir separadamente a edição anual Bíblia + Chimarrão 2027.</small>", "<small>A criação da conta não gera cobrança. Você poderá conhecer o aplicativo e adquirir separadamente o acesso premium Bíblia + Chimarrão — Edição 2027.</small>")
text = text.replace("setUser(data.user)\n          setScreen('annualPurchase')", "setUser(data.user)\n          setScreen('dashboard')", 1)
text = text.replace("<p>Conheça a proposta do devocional e crie sua conta para acessar os recursos disponíveis.</p><div className=\"guest-demo-actions\"><button onClick={()=>setScreen('signup')}>Criar minha conta</button>", "<p>Conheça a proposta do aplicativo. Os encontros completos são liberados com a aquisição do acesso premium da Edição 2027.</p><div className=\"guest-demo-actions\"><button onClick={()=>setScreen('signup')}>Criar minha conta</button>")
text = text.replace("<p>Conheça a proposta do devocional. Os encontros completos são liberados com a aquisição da edição anual 2027.</p><div className=\"guest-demo-actions\"><button onClick={()=>setScreen('signup')}>Criar conta e adquirir 2027</button>", "<p>Conheça a proposta do aplicativo. Os encontros completos são liberados com a aquisição do acesso premium da Edição 2027.</p><div className=\"guest-demo-actions\"><button onClick={()=>setScreen('signup')}>Criar minha conta</button>")
text = text.replace("{!user && <section className=\"guest-demo-hint guest-demo-start\"><h2>Experimente antes de criar sua conta</h2><p>Conheça os doze meses e leia gratuitamente os três primeiros encontros de janeiro.</p><button onClick={()=>openEncounter(1)}>Ler o primeiro encontro →</button></section>}", "{!user && <section className=\"guest-demo-hint guest-demo-start\"><h2>Conheça a edição 2027</h2><p>Veja os doze meses, os temas e a estrutura da caminhada. Os encontros completos são conteúdo do acesso premium anual.</p><button onClick={()=>setScreen('signup')}>Criar minha conta →</button></section>}")
text = text.replace("{!user && <section className=\"guest-demo-hint guest-demo-start\"><h2>Gostou da apresentação?</h2><p>Leia o primeiro encontro e conheça o conteúdo do devocional antes de se cadastrar.</p><button onClick={()=>openEncounter(1)}>Ler o primeiro encontro gratuitamente →</button></section>}", "{!user && <section className=\"guest-demo-hint guest-demo-start\"><h2>Gostou da apresentação?</h2><p>Crie sua conta gratuitamente para conhecer o aplicativo. O acesso premium da Edição 2027 pode ser adquirido depois.</p><button onClick={()=>setScreen('signup')}>Criar minha conta →</button></section>}")
text = text.replace("onClick={() => user || day.day_number<=3 ? openEncounter(day.day_number) : setScreen('guestInfo')}", "onClick={() => user ? openEncounter(day.day_number) : setScreen('signup')}")
text = text.replace("{!user && day.day_number>3 ? \"🔒\" : \"›\"}", "{!user ? \"🔒\" : \"›\"}")
text = text.replace("<p>Explore os recursos e experimente gratuitamente os três primeiros encontros. Para registrar sua caminhada, crie uma conta.</p><button onClick={()=>setScreen(\"devotional\")}>Experimentar 3 encontros</button>", "<p>Explore os recursos, os meses e os temas da edição 2027. Os encontros completos são liberados pelo acesso premium anual.</p><button onClick={()=>setScreen(\"guestDemo\")}>Conhecer a edição 2027</button>")

text = text.replace("commercialCatalog['devocional_chimarrao_com_deus_2027']", "commercialCatalog['app_biblia_chimarrao']")
text = text.replace("product_code:'devocional_chimarrao_com_deus_2027'", "product_code:'app_biblia_chimarrao'")

old_restricted = """  if (screen === 'accessRestricted' && user) return <main className=\"dashboard\"><header className=\"dash-header\"><div><strong>BÍBLIA + CHIMARRÃO</strong><small>Controle de acesso</small></div><button className=\"logout\" onClick={()=>setScreen('dashboard')}>← Menu</button></header><section className=\"admin-shell\"><div className=\"admin-hero\"><p className=\"eyebrow\">ÁREA DO LEITOR</p><h1>Acesso restrito</h1><p>{message || 'Seu acesso ao conteúdo protegido ainda não está liberado.'}</p><button type=\"button\" onClick={()=>setScreen('dashboard')}>Voltar ao menu</button></div></section></main>"""
new_restricted = """  if (screen === 'accessRestricted' && user) {\n    const annualProduct=commercialCatalog['app_biblia_chimarrao']\n    const annualPrice=annualProduct?formatCommercialPrice(annualProduct):'R$ 34,90'\n    return <main className=\"dashboard\"><header className=\"dash-header\"><div><strong>BÍBLIA + CHIMARRÃO</strong><small>Edição 2027</small></div><button className=\"logout\" onClick={()=>setScreen('dashboard')}>← Menu</button></header><section className=\"admin-shell\"><div className=\"admin-hero\"><p className=\"eyebrow\">ACESSO PREMIUM 2027</p><h1>Bíblia + Chimarrão — Edição 2027</h1><p>Tenha acesso aos 365 encontros de 2027, Minha Caminhada, favoritos, anotações e aos recursos premium da edição.</p><h2>{annualPrice} <small>· pagamento único para a Edição 2027</small></h2>{message&&message!=='Seu acesso ainda não está liberado.'&&<p>{message}</p>}<button type=\"button\" onClick={()=>{setAnnualPurchaseMessage('');setScreen('annualPurchase');window.scrollTo(0,0)}} disabled={!annualProduct?.isActive}>Adquirir Edição 2027 — {annualPrice}</button><p><small>Pagamento processado com segurança pelo Mercado Pago.</small></p><hr/><h3>Já recebeu seu acesso pela sua empresa?</h3><p>Se sua empresa adquiriu uma licença para você, o administrador pode liberar sua conta sem pagamento individual.</p><button type=\"button\" className=\"logout\" onClick={()=>setScreen('dashboard')}>Voltar ao menu</button></div></section></main>\n  }"""
text = text.replace(old_restricted, new_restricted)

return_effect = """\n  useEffect(()=>{\n    const params=new URLSearchParams(window.location.search)\n    const payment=params.get('payment')\n    if(!['success','pending','failure'].includes(payment))return\n    setPaymentReturn(payment)\n    setScreen('paymentReturn')\n    window.history.replaceState({},document.title,window.location.pathname)\n  },[])\n"""
if "setScreen('paymentReturn')" not in text:
    marker = "  useEffect(()=>{\n    if(!user||!supabase){setIsAdmin(false);return}"
    text = text.replace(marker, return_effect + "\n" + marker, 1)

anchor = "  if (screen === 'login' || screen === 'signup') {"
if "screen === 'annualPurchase'" not in text:
    annual = """  async function purchaseAnnualEdition(){\n    const product=commercialCatalog['app_biblia_chimarrao']\n    if(!user||!supabase||!product?.isActive){setAnnualPurchaseMessage('O acesso premium da Edição 2027 ainda não está disponível para compra.');return}\n    setAnnualPurchaseBusy(true);setAnnualPurchaseMessage('Preparando checkout seguro do Mercado Pago...')\n    const {data:sessionData}=await supabase.auth.getSession();const session=sessionData?.session\n    if(!session){setAnnualPurchaseBusy(false);setAnnualPurchaseMessage('Sua sessão expirou. Entre novamente para continuar.');return}\n    try{\n      const response=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/mercado-pago-create-order`,{method:'POST',headers:{'Content-Type':'application/json','apikey':import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({product_code:'app_biblia_chimarrao',accepted:true,return_base_url:window.location.origin})})\n      let data={};try{data=await response.json()}catch{}\n      if(!response.ok||!data?.checkout_url){setAnnualPurchaseMessage('Não foi possível iniciar a compra: '+(data?.error||('erro '+response.status))+'.');setAnnualPurchaseBusy(false);return}\n      window.location.assign(data.checkout_url)\n    }catch{setAnnualPurchaseMessage('Não foi possível conectar ao checkout do Mercado Pago.');setAnnualPurchaseBusy(false)}\n  }\n\n  if(screen === 'annualPurchase' && user) return <AnnualPurchasePanel product={commercialCatalog['app_biblia_chimarrao']} busy={annualPurchaseBusy} message={annualPurchaseMessage} onBack={()=>setScreen('dashboard')} onContinue={purchaseAnnualEdition}/>\n\n"""
    text = text.replace(anchor, annual + anchor)
else:
    text = text.replace("body:JSON.stringify({product_code:'app_biblia_chimarrao',accepted:true})", "body:JSON.stringify({product_code:'app_biblia_chimarrao',accepted:true,return_base_url:window.location.origin})")

if "screen === 'paymentReturn'" not in text:
    payment_panel = """  if(screen === 'paymentReturn') {\n    const approved=paymentReturn==='success'\n    const pending=paymentReturn==='pending'\n    return <main className=\"dashboard payment-return-page\"><header className=\"dash-header\"><div><strong>BÍBLIA + CHIMARRÃO</strong><small>Retorno do pagamento · Edição 2027</small></div></header><section className=\"admin-shell\"><div className=\"admin-hero payment-return-card\"><p className=\"eyebrow\">{approved?'PAGAMENTO RECEBIDO':pending?'CONFIRMAÇÃO EM ANDAMENTO':'PAGAMENTO NÃO CONCLUÍDO'}</p><h1>{approved?'Obrigado! Estamos confirmando seu acesso.':pending?'Seu pagamento está sendo confirmado.':'O pagamento não foi concluído.'}</h1><p>{approved?'A confirmação segura é feita pelo nosso sistema. Se o Mercado Pago já confirmou a transação, sua Edição 2027 estará disponível na conta.':pending?'Não é necessário pagar novamente. Aguarde a confirmação do Mercado Pago e volte para sua conta.':'Nenhum acesso é liberado por esta tela. Você pode voltar ao aplicativo e tentar novamente quando desejar.'}</p>{user?<><button type=\"button\" onClick={async()=>{await loadBookAccess();setPaymentReturn(null);setScreen('dashboard');window.scrollTo(0,0)}}>{approved?'Entrar no Bíblia + Chimarrão':'Voltar ao aplicativo'}</button>{approved&&<button type=\"button\" className=\"logout\" onClick={async()=>{setPaymentReturn(null);await openEncounter(1)}}>Entrar no Devocional →</button>}</>:<><p><strong>Entre na mesma conta usada na compra para verificar sua liberação.</strong></p><button type=\"button\" onClick={()=>setScreen('login')}>Entrar na minha conta</button></>}</div></section></main>\n  }\n\n"""
    text = text.replace(anchor, payment_panel + anchor, 1)

# Recuperação de senha no laboratório.
recovery_states = """  const [recoveryEmail,setRecoveryEmail]=useState('')\n  const [recoveryPassword,setRecoveryPassword]=useState('')\n  const [recoveryConfirm,setRecoveryConfirm]=useState('')\n  const [recoveryMessage,setRecoveryMessage]=useState('')\n  const [recoveryBusy,setRecoveryBusy]=useState(false)\n"""
if "const [recoveryEmail" not in text:
    text = text.replace("  const [showPassword, setShowPassword] = useState(false)\n", "  const [showPassword, setShowPassword] = useState(false)\n" + recovery_states)

old_listener = """    const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => {\n      setUser(session?.user ?? null)\n    })"""
new_listener = """    const { data: listener } = supabase.auth.onAuthStateChange((event, session) => {\n      setUser(session?.user ?? null)\n      if(event==='PASSWORD_RECOVERY'){setRecoveryMessage('');setRecoveryPassword('');setRecoveryConfirm('');setScreen('resetPassword')}\n    })"""
text = text.replace(old_listener,new_listener)

recovery_functions = """\n  async function requestPasswordRecovery(event){\n    event.preventDefault()\n    const target=(recoveryEmail||email).trim()\n    if(!target||!supabase){setRecoveryMessage('Informe o e-mail da sua conta.');return}\n    setRecoveryBusy(true);setRecoveryMessage('Enviando link seguro...')\n    const redirectTo=window.location.origin+'/?password_recovery=1'\n    const {error}=await supabase.auth.resetPasswordForEmail(target,{redirectTo})\n    setRecoveryBusy(false)\n    if(error){setRecoveryMessage('Não foi possível enviar o link agora. Confira o e-mail e tente novamente.');return}\n    setRecoveryMessage('Se esse e-mail estiver cadastrado, você receberá um link para criar uma nova senha. Confira também a pasta de spam.')\n  }\n\n  async function finishPasswordRecovery(event){\n    event.preventDefault()\n    if(recoveryPassword.length<8){setRecoveryMessage('A nova senha precisa ter pelo menos 8 caracteres.');return}\n    if(recoveryPassword!==recoveryConfirm){setRecoveryMessage('As duas senhas não são iguais.');return}\n    setRecoveryBusy(true);setRecoveryMessage('Salvando sua nova senha...')\n    const {error}=await supabase.auth.updateUser({password:recoveryPassword})\n    setRecoveryBusy(false)\n    if(error){setRecoveryMessage('Não foi possível alterar a senha. O link pode ter expirado; solicite uma nova recuperação.');return}\n    setRecoveryPassword('');setRecoveryConfirm('');setRecoveryMessage('✓ Senha alterada com sucesso. Você já pode continuar no aplicativo.')\n  }\n\n"""
if "async function requestPasswordRecovery" not in text:
    text = text.replace("  async function purchaseAnnualEdition(){", recovery_functions + "  async function purchaseAnnualEdition(){",1)

forgot_button = """          {!creating && <button type=\"button\" className=\"legal-link\" onClick={()=>{setRecoveryEmail(email);setRecoveryMessage('');setScreen('forgotPassword')}}>Esqueci minha senha</button>}\n"""
if "setScreen('forgotPassword')" not in text:
    text = text.replace("          <button type=\"submit\" disabled={loading}>{loading ? 'Aguarde...' : creating ? 'Criar minha conta' : 'Entrar'}</button>\n", "          <button type=\"submit\" disabled={loading}>{loading ? 'Aguarde...' : creating ? 'Criar minha conta' : 'Entrar'}</button>\n" + forgot_button,1)

recovery_screens = """  if(screen==='forgotPassword') return <main className=\"app\"><section className=\"auth-card\"><button className=\"back-button\" onClick={()=>{setRecoveryMessage('');setScreen('login')}}>← Voltar</button><p className=\"eyebrow\">BÍBLIA + CHIMARRÃO</p><h2>Recuperar minha senha</h2><p className=\"auth-intro\">Informe o e-mail da sua conta. Enviaremos um link seguro para você criar uma nova senha.</p><form className=\"auth-form\" onSubmit={requestPasswordRecovery}><label>E-mail<input type=\"email\" value={recoveryEmail} onChange={e=>setRecoveryEmail(e.target.value)} autoComplete=\"email\" required/></label><button type=\"submit\" disabled={recoveryBusy}>{recoveryBusy?'Enviando...':'Enviar link de recuperação'}</button></form>{recoveryMessage&&<p className=\"form-message\" role=\"status\">{recoveryMessage}</p>}</section></main>\n\n  if(screen==='resetPassword') return <main className=\"app\"><section className=\"auth-card\"><p className=\"eyebrow\">BÍBLIA + CHIMARRÃO</p><h2>Criar nova senha</h2><p className=\"auth-intro\">Digite uma nova senha para sua conta.</p><form className=\"auth-form\" onSubmit={finishPasswordRecovery}><label>Nova senha<input type=\"password\" minLength=\"8\" autoComplete=\"new-password\" value={recoveryPassword} onChange={e=>setRecoveryPassword(e.target.value)} required/></label><label>Confirmar nova senha<input type=\"password\" minLength=\"8\" autoComplete=\"new-password\" value={recoveryConfirm} onChange={e=>setRecoveryConfirm(e.target.value)} required/></label><button type=\"submit\" disabled={recoveryBusy}>{recoveryBusy?'Salvando...':'Salvar nova senha'}</button></form>{recoveryMessage&&<p className=\"form-message\" role=\"status\">{recoveryMessage}</p>}{recoveryMessage.startsWith('✓')&&<button type=\"button\" onClick={()=>setScreen(user?'dashboard':'login')}>Continuar no aplicativo →</button>}</section></main>\n\n"""
if "screen==='forgotPassword'" not in text:
    text = text.replace(anchor,recovery_screens+anchor,1)

path.write_text(text, encoding='utf-8')
print('Laboratório aplicado: compra anual, retorno seguro e recuperação de senha.')
