name: Validar aplicativo
on:
  pull_request:
    branches: [main]
  push:
    branches: [lab-commercial-prices-2026-10-07]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Instalar dependências
        run: npm install
      - name: Compilar aplicativo
        run: npm run build
